/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2018-06-18 09:54:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class mainBottom_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>My JSP 'mainBottom.jsp' starting page</title>\r\n");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("  \r\n");
      out.write("    <div id=\"func\" style=\"position: absolute; height: 600px; width: 1260px;\">\r\n");
      out.write("    \r\n");
      out.write("    \t<div class=\"func\" id=\"extFunc\" style=\"position: absolute; left: 0px; top: 0px; width: 1260px; height: 200px;\">\r\n");
      out.write("    \t\t<label style=\"position: absolute; top: 20px; left: 510px;\">\r\n");
      out.write("    \t\t\t<font size=\"20\" color=\"red\">叫牌练习</font>\r\n");
      out.write("    \t\t</label>\r\n");
      out.write("    \t\t<a href=\"jsp/user/historyList.jsp\" target=\"bottom\"><img alt=\"叫牌历史纪录\" title=\"叫牌历史纪录\" src=\"./picture/bg/historyRecord_bg.jpg\" style=\"position: absolute; top: 20px; right: 100px;\"></a>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    \t\r\n");
      out.write("    \t<div class=\"func\" id=\"baseFunc\" style=\"position: absolute; left: 0px; top: 200px; width: 1260px; height: 400px;\">\r\n");
      out.write("    \t\t<a href=\"jsp/Licensing.jsp\" target=\"bottom\"><img alt=\"单人叫牌练习\" title=\"单人叫牌练习\" src=\"./picture/bg/licensing_bg.PNG\" style=\"position: absolute; top: 20px; left: 420px;\"></a>\r\n");
      out.write("    \t\t<a href=\"jsp/user/historyList.jsp\" target=\"bottom\"><img alt=\"查看他人叫牌记录\" title=\"查看他人叫牌记录\" src=\"./picture/bg/searchRecord_bg.PNG\" style=\"position: absolute; top: 20px; right: 400px;\"></a>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
