/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2018-06-04 09:51:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import impl.*;

public final class contractTable_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>桥牌发牌页面</title>\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("\t\t.main {\r\n");
      out.write("\t\t\tposition: absolute;\r\n");
      out.write("\t\t\ttext-align: center; /*让div内部文字居中*/\r\n");
      out.write("\t\t\tbackground-color: #fff;\r\n");
      out.write("\t\t\tborder-radius: 20px;\r\n");
      out.write("\t\t\tbottom: 0px;\r\n");
      out.write("\t\t\tmargin: auto;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body style=\"position: absolute;\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- 叫牌主界面的设计 -->\r\n");
      out.write("\t<div class=\"main\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 叫牌表格的设计 -->\r\n");
      out.write("\t\t<div class=\"callTable\"\r\n");
      out.write("\t\t\tstyle=\"width: 300px; height: 100px; overflow-y: scroll; scrollbar-base-color: #ff6600; border: 1px solid;\">\r\n");
      out.write("\t\t\t<table id=\"data\" style=\"width: 100%; height: 100%; text-align: center;\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>N</th>\r\n");
      out.write("\t\t\t\t\t<th>E</th>\r\n");
      out.write("\t\t\t\t\t<th>S</th>\r\n");
      out.write("\t\t\t\t\t<th>W</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr id=\"DataTr0\">\r\n");
      out.write("\t\t\t\t\t<td id=\"DataTr0Td0\"></td>\r\n");
      out.write("\t\t\t\t\t<td id=\"DataTr0Td1\"></td>\r\n");
      out.write("\t\t\t\t\t<td id=\"DataTr0Td2\"></td>\r\n");
      out.write("\t\t\t\t\t<td id=\"DataTr0Td3\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 叫牌定约卡的设计 -->\r\n");
      out.write("\t\t<div class=\"contractCard\" style=\"width: 300px; height: 250px; border: 1px solid;\">\r\n");
      out.write("\t\t\t<table style=\"width: 100%; height: 85%\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button0\" type=\"button\" value=\"1C\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button1\" type=\"button\" value=\"1D\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button2\" type=\"button\" value=\"1H\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button3\" type=\"button\" value=\"1S\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button4\" type=\"button\" value=\"1NT\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button5\" type=\"button\" value=\"2C\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button6\" type=\"button\" value=\"2D\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button7\" type=\"button\" value=\"2H\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button8\" type=\"button\" value=\"2S\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button9\" type=\"button\" value=\"2NT\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button10\" type=\"button\" value=\"3C\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button11\" type=\"button\" value=\"3D\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button12\" type=\"button\" value=\"3H\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button13\" type=\"button\" value=\"3S\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button14\" type=\"button\" value=\"3NT\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button15\" type=\"button\" value=\"4C\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button16\" type=\"button\" value=\"4D\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button17\" type=\"button\" value=\"4H\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button18\" type=\"button\" value=\"4S\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button19\" type=\"button\" value=\"4NT\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button20\" type=\"button\" value=\"5C\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button21\" type=\"button\" value=\"5D\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button22\" type=\"button\" value=\"5H\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button23\" type=\"button\" value=\"5S\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button24\" type=\"button\" value=\"5NT\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button25\" type=\"button\" value=\"6C\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button26\" type=\"button\" value=\"6D\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button27\" type=\"button\" value=\"6H\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button28\" type=\"button\" value=\"6S\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button29\" type=\"button\" value=\"6NT\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button30\" type=\"button\" value=\"7C\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button31\" type=\"button\" value=\"7D\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button32\" type=\"button\" value=\"7H\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button33\" type=\"button\" value=\"7S\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button34\" type=\"button\" value=\"7NT\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<table style=\"width: 100%; height: 10%\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button35\" type=\"button\" value=\"Pass\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"button36\" type=\"button\" value=\"Dbl\" onclick=\"callCard()\"/></td>\r\n");
      out.write("\t\t\t\t\t<td style=\"text-align: center; color: red\"><span id=\"countdown\">30</span><span>s</span></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("  \r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
