/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2018-06-17 12:45:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>用户注册</title>\r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/index.css\">\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar code; //在全局定义验证码\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//产生验证码\r\n");
      out.write("\t\tfunction createVerCode(){\r\n");
      out.write("\t\t    code = \"\";\r\n");
      out.write("\t\t    var codeLength = 4;//验证码的长度\r\n");
      out.write("\t\t    var checkCode = document.getElementById(\"code\");\r\n");
      out.write("\t\t    var random = new Array(0,1,2,3,4,5,6,7,8,9,'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R', 'S','T','U','V','W','X','Y','Z');//随机数\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    for(var i = 0; i < codeLength; i++) {//循环操作  \r\n");
      out.write("\t\t        var index = Math.floor(Math.random()*36);//取得随机数的索引（0~35）  \r\n");
      out.write("\t\t        code += random[index];//根据索引取得随机数加到code上  \r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t    checkCode.value = code;//把code值赋给验证码 \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction check() {\r\n");
      out.write("\t\t\tvar userName = document.getElementById(\"user_name\").value;   // 获取输入框中的用户名\r\n");
      out.write("\t\t\tvar userPWD = document.getElementById(\"user_pwd\").value; // 获取输入框中的密码\r\n");
      out.write("\t\t\tvar userCode = document.getElementById(\"verification_code\");  // 获取输入框中的验证码\r\n");
      out.write("\t\t\tvar checkCode = document.getElementById(\"code\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//-- 验证用户名\r\n");
      out.write("\t\t\tif(userName == \"\") {\r\n");
      out.write("\t\t\t\talert(\"用户名不能为空！\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//-- 验证密码\r\n");
      out.write("\t\t\tif(userPWD == \"\") {\r\n");
      out.write("\t\t\t\talert(\"密码不能为空！\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//-- 验证验证码\r\n");
      out.write("\t\t\tif(checkCode.value.length == 5) {\r\n");
      out.write("\t\t\t\talert(\"尚未获取验证码！\");\r\n");
      out.write("\t\t\t\tuserCode.value = \"\";\r\n");
      out.write("\t\t\t\tcreateVerCode();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(userCode.value != checkCode.value) {\r\n");
      out.write("\t\t\t\talert(\"验证码错误!\");\r\n");
      out.write("\t\t\t\tuserCode.value = \"\";\r\n");
      out.write("\t\t\t\tcreateVerCode();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("    <form action=\"check\" method=\"post\" id=\"myForm\" name=\"myForm\" onsubmit=\"return check()\" autocomplete=\"off\">\r\n");
      out.write("    <div align=\"center\">\r\n");
      out.write("    \t<table height=\"500px\">\r\n");
      out.write("    \t\t<tr>\r\n");
      out.write("    \t\t\t<th colspan=\"3\" align=\"center\"> <font class=\"title\">欢迎注册桥牌叫牌练习网站</font> </th>\r\n");
      out.write("    \t\t</tr>\r\n");
      out.write("    \t\t<tr height=\"150px\">\r\n");
      out.write("    \t\t</tr>\r\n");
      out.write("    \t\t<tr class=\"line\">\r\n");
      out.write("    \t\t\t<td align=\"right\" class=\"load_font\">用户名：</td>\r\n");
      out.write("\t\t\t\t<td align=\"center\" width=\"30px\"> <input type=\"text\" id=\"user_name\" name=\"user_name\" maxlength=\"20\"> </td>\r\n");
      out.write("\t\t\t\t<td align=\"left\" class=\"load_font\">*(1~20位字符)</td>\r\n");
      out.write("    \t\t</tr>\r\n");
      out.write("    \t\t<tr class=\"line\">\r\n");
      out.write("    \t\t\t<td align=\"right\" class=\"load_font\">密码：</td>\r\n");
      out.write("\t\t\t\t<td align=\"center\" width=\"30px\"> <input type=\"password\" id=\"user_pwd\" name=\"user_pwd\" maxlength=\"20\"> </td>\r\n");
      out.write("\t\t\t\t<td align=\"left\" class=\"load_font\">*(1~20位字符)</td>\r\n");
      out.write("    \t\t</tr>\r\n");
      out.write("    \t\t<tr class=\"line\">\r\n");
      out.write("    \t\t\t<td align=\"right\" class=\"load_font\">密码：</td>\r\n");
      out.write("\t\t\t\t<td align=\"center\" width=\"30px\"> <input type=\"password\" id=\"user_pwd1\" name=\"user_pwd1\" maxlength=\"20\"> </td>\r\n");
      out.write("\t\t\t\t<td align=\"left\" class=\"load_font\">*(1~20位字符)</td>\r\n");
      out.write("    \t\t</tr>\r\n");
      out.write("    \t\t<tr class=\"line\">\r\n");
      out.write("    \t\t\t<td align=\"right\" class=\"load_font\">手机号：</td>\r\n");
      out.write("\t\t\t\t<td align=\"center\" width=\"30px\"> <input type=\"text\" id=\"user_phone\" name=\"user_phone\" maxlength=\"11\"> </td>\r\n");
      out.write("\t\t\t\t<td align=\"left\" class=\"load_font\">*(11位数字)</td>\r\n");
      out.write("    \t\t</tr>\r\n");
      out.write("    \t\t<tr class=\"line\">\r\n");
      out.write("    \t\t\t<td align=\"right\" class=\"load_font\">地址：</td>\r\n");
      out.write("\t\t\t\t<td align=\"center\" width=\"30px\"> <input type=\"text\" id=\"user_address\" name=\"user_address\" maxlength=\"45\"> </td>\r\n");
      out.write("\t\t\t\t<td align=\"left\" class=\"load_font\">*(1~45位字符)</td>\r\n");
      out.write("    \t\t</tr>\r\n");
      out.write("    \t\t<tr class=\"line\">\r\n");
      out.write("    \t\t\t<td align=\"right\" class=\"load_font\">级别：</td>\r\n");
      out.write("\t\t\t\t<td align=\"center\" width=\"30px\"> \r\n");
      out.write("\t\t\t\t\t<select id=\"select_rank\" name=\"select_rank\">\r\n");
      out.write("\t\t\t\t\t\t<option id=\"select1\">新手\r\n");
      out.write("\t\t\t\t\t\t<option id=\"select2\">上手\r\n");
      out.write("\t\t\t\t\t\t<option id=\"select3\">中等\r\n");
      out.write("\t\t\t\t\t\t<option id=\"select4\">高手\r\n");
      out.write("\t\t\t\t\t\t<option id=\"select5\">大师\r\n");
      out.write("\t\t\t\t\t\t<option id=\"select6\">传说\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("    \t\t</tr>\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t<tr height=\"40px\" >\r\n");
      out.write("    \t\t\t<td colspan=\"2\" align=\"right\">\r\n");
      out.write("    \t\t\t\t<input type=\"submit\" value=\"注册\" class=\"upload\" /> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;\r\n");
      out.write("    \t\t\t\t<input type=\"reset\" value=\"重置\" class=\"upload\" />\r\n");
      out.write("    \t\t\t</td>\r\n");
      out.write("    \t\t</tr>\r\n");
      out.write("    \t</table>\r\n");
      out.write("    </div>\r\n");
      out.write("    </form>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
