/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2018-06-15 13:39:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>用户登录</title>\r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/index.css\">\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar size = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.allUserID.size()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction check() {\r\n");
      out.write("\t\t\tvar userID = document.getElementById(\"user_id\").value;   // 获取输入框中的员工号\r\n");
      out.write("\t\t\tvar userPWD = document.getElementById(\"user_pwd\").value; // 获取输入框中的密码\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tif(userID == \"\") {\r\n");
      out.write("\t\t\t\talert(\"用户名不能为空！\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//-- 验证密码\r\n");
      out.write("\t\t\tif(userPWD == \"\") {\r\n");
      out.write("\t\t\t\talert(\"密码不能为空！\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction validate_name() {\r\n");
      out.write("\t\t\tvar i = 0;\r\n");
      out.write("\t\t\tvar hasUser = false;          // 判断该员工是否存在\r\n");
      out.write("\t\t\tvar userID = document.getElementById(\"user_id\").value;   // 获取输入框中的员工号\r\n");
      out.write("\t\t\tvar list = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.allUserID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(";              // 获取会话对象\r\n");
      out.write("\t\t\twhile(i < size) {\r\n");
      out.write("\t\t\t\tvar context = list[i] + \"\";\r\n");
      out.write("\t\t\t\tif(userID == context) {\r\n");
      out.write("\t\t\t\t\thasUser = true;\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\ti++;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(!hasUser) {\r\n");
      out.write("\t\t\t\talert(\"员工号不存在!\");\r\n");
      out.write("\t\t\t\tlocation.reload(false);     // 员工号不存在，重新载入页面\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("    <form action=\"check\" method=\"post\" id=\"myForm\" name=\"myForm\" onsubmit=\"return check()\">\r\n");
      out.write("    <div align=\"center\">\r\n");
      out.write("    \t<table height=\"500px\">\r\n");
      out.write("    \t\t<tr>\r\n");
      out.write("    \t\t\t<th colspan=\"2\" align=\"center\"> <font class=\"title\">欢迎登录图灵软件公司</font> </th>\r\n");
      out.write("    \t\t</tr>\r\n");
      out.write("    \t\t<tr height=\"150px\">\r\n");
      out.write("    \t\t</tr>\r\n");
      out.write("    \t\t<tr class=\"line\">\r\n");
      out.write("    \t\t\t<td align=\"right\" class=\"load_font\">员工号：</td>\r\n");
      out.write("\t\t\t\t<td> <input type=\"text\" id=\"user_id\" name=\"user_id\" onBlur=\"validate_name()\"/> </td>\r\n");
      out.write("    \t\t</tr>\r\n");
      out.write("    \t\t<tr class=\"line\">\r\n");
      out.write("    \t\t\t<td align=\"right\" class=\"load_font\">密码：</td>\r\n");
      out.write("\t\t\t\t<td> <input type=\"password\" id=\"user_pwd\" name=\"user_pwd\"/> </td>\r\n");
      out.write("    \t\t</tr>\r\n");
      out.write("    \t\t<tr height=\"40px\" >\r\n");
      out.write("    \t\t\t<td colspan=\"2\" style=\"padding-left: 100px\">\r\n");
      out.write("    \t\t\t\t<input type=\"submit\" value=\"登录\" class=\"upload\" /> &nbsp; &nbsp; &nbsp;\r\n");
      out.write("    \t\t\t\t<input type=\"reset\" value=\"重置\" class=\"upload\" /> &nbsp; &nbsp; &nbsp;\r\n");
      out.write("    \t\t\t</td>\r\n");
      out.write("    \t\t</tr>\r\n");
      out.write("    \t</table>\r\n");
      out.write("    </div>\r\n");
      out.write("    </form>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
